spaceone-dev/plugin-azure-cloud-service-inven-collector

src/spaceone/inventory/libs/schema/region.py, src/spaceone/inventory/manager/disk_manager.py, src/spaceone/inventory/model/disk/cloud_service.py, src/spaceone/inventory/model/disk/cloud_service_type.py, src/spaceone/inventory/model/disk/data.py, src/spaceone/inventory/service/collector_service.py, test/connector/test_disk_connector.py
=> update disk model data

src/spaceone/inventory/connector/disk.py, src/spaceone/inventory/manager/disk_manager.py, src/spaceone/inventory/model/disk/cloud_service.py, src/spaceone/inventory/model/disk/cloud_service_type.py, src/spaceone/inventory/model/disk/data.py
=> revise data model and manager

pkg/pip_requirements.txt, src/spaceone/inventory/libs/connector.py, src/spaceone/inventory/manager/disk_manager.py, src/spaceone/inventory/model/disk/cloud_service.py, src/spaceone/inventory/model/disk/data.py
Update Disk model, Connector, Manager
=> Update Disk model, Connector, Manager

src/spaceone/inventory/model/disk/cloud_service_type.py
=> change azure-disk icon uri

src/spaceone/inventory/model/disk/cloud_service.py, src/spaceone/inventory/model/disk/cloud_service_type.py
=> Revise disk states and colors

src/spaceone/inventory/model/snapshot/cloud_service.py
Revise error (Disk source vm name)
=> Revise error (Disk source vm name)

src/spaceone/inventory/connector/__init__.py, src/spaceone/inventory/connector/vmscaleset.py, src/spaceone/inventory/manager/vmscaleset_manager.py, src/spaceone/inventory/model/vmscaleset/cloud_service.py, src/spaceone/inventory/model/vmscaleset/cloud_service_type.py, src/spaceone/inventory/model/vmscaleset/data.py
Initial commits for VMSS plugin
=> Initial commits for VMSS plugin

src/spaceone/inventory/model/vmscaleset/data.py
=> Update VmScaleSet data model

src/spaceone/inventory/model/disk/cloud_service.py, src/spaceone/inventory/model/disk/cloud_service_type.py, src/spaceone/inventory/model/snapshot/cloud_service.py, src/spaceone/inventory/model/snapshot/cloud_service_type.py
=> Delete Sizefield options

src/spaceone/inventory/conf/global_conf.py
=> Add secret data masking

src/spaceone/inventory/model/disk/cloud_service_type.py, src/spaceone/inventory/model/snapshot/cloud_service_type.py, src/spaceone/inventory/model/vmscaleset/cloud_service_type.py
Add cloud service type service code
=> Add cloud service type service code

src/spaceone/inventory/api/plugin/collector.py, src/spaceone/inventory/connector/vmscaleset.py, src/spaceone/inventory/libs/manager.py, src/spaceone/inventory/manager/vmscaleset_manager.py, src/spaceone/inventory/model/disk/cloud_service_type.py, src/spaceone/inventory/model/snapshot/cloud_service_type.py, src/spaceone/inventory/model/vmscaleset/cloud_service.py, src/spaceone/inventory/model/vmscaleset/cloud_service_type.py, src/spaceone/inventory/model/vmscaleset/data.py, src/spaceone/inventory/service/collector_service.py
Update virtual machine scale set model, manager, and service
=> Update virtual machine scale set model, manager, and service

src/spaceone/inventory/service/collector_service.py
Add comma to collector services
=> Add comma to collector services

src/spaceone/inventory/model/vmscaleset/cloud_service.py, src/spaceone/inventory/model/vmscaleset/data.py
Update cloud_service OS disk layout type
=> Update OS disk layout type of vmss cloud_service

src/spaceone/inventory/manager/vmscaleset_manager.py, src/spaceone/inventory/model/vmscaleset/cloud_service.py, src/spaceone/inventory/model/vmscaleset/data.py
- instance status profile
- settings (string type -> object type
=> update instance status profile, settings

src/spaceone/inventory/manager/vmscaleset_manager.py, src/spaceone/inventory/model/vmscaleset/cloud_service.py, src/spaceone/inventory/model/vmscaleset/data.py
=> Instance state error fix

src/spaceone/inventory/model/vmscaleset/cloud_service.py
Update instance status to EnumDyField
=> Update instance status to EnumDyField

src/spaceone/inventory/service/collector_service.py
add supported_features (garbage_collection)
=> add supported_features (garbage_collection)

README.md, pkg/pip_requirements.txt, src/spaceone/inventory/connector/__init__.py, src/spaceone/inventory/connector/loadbalncer.py, src/spaceone/inventory/libs/connector.py, src/spaceone/inventory/libs/schema/cloud_service.py, src/spaceone/inventory/manager/disk_manager.py, src/spaceone/inventory/manager/loadbalancer_manager.py, src/spaceone/inventory/manager/snapshot_manager.py, src/spaceone/inventory/manager/vmscaleset_manager.py, src/spaceone/inventory/model/loadbalancer/cloud_service.py, src/spaceone/inventory/model/loadbalancer/cloud_service_type.py, src/spaceone/inventory/model/loadbalancer/data.py, src/spaceone/inventory/model/vmscaleset/cloud_service.py, src/spaceone/inventory/model/vmscaleset/data.py, src/spaceone/inventory/service/collector_service.py, test/connector/test_load_balancer_connector.py, test/manager/test_load_balancer_manager.py
=> Add tags and add readme

src/spaceone/inventory/service/collector_service.py
=> Update collector service

src/spaceone/inventory/connector/loadbalncer.py, src/spaceone/inventory/manager/__init__.py, src/spaceone/inventory/manager/loadbalancer_manager.py, src/spaceone/inventory/model/loadbalancer/cloud_service.py, src/spaceone/inventory/model/loadbalancer/cloud_service_type.py, src/spaceone/inventory/model/loadbalancer/data.py, src/spaceone/inventory/service/collector_service.py
Add Load Balancer manager, service, and model
=> Update Load Balancer manager, service, and model (Backend pool vms)

src/spaceone/inventory/model/loadbalancer/cloud_service.py, src/spaceone/inventory/model/loadbalancer/data.py
[BUG-FIX] LB backend pool data model
=> [BUG-FIX] LB backend pool data model

pkg/pip_requirements.txt, src/spaceone/inventory/connector/__init__.py, src/spaceone/inventory/connector/sql.py, src/spaceone/inventory/libs/connector.py, src/spaceone/inventory/libs/manager.py, src/spaceone/inventory/manager/sql_database_manager.py, src/spaceone/inventory/manager/sql_server_manager.py, src/spaceone/inventory/model/sqldatabase/cloud_service.py, src/spaceone/inventory/model/sqldatabase/cloud_service_type.py, src/spaceone/inventory/model/sqldatabase/data.py, src/spaceone/inventory/model/sqlserver/cloud_service.py, src/spaceone/inventory/model/sqlserver/cloud_service_type.py, src/spaceone/inventory/model/sqlserver/data.py, test/manager/test_sql_server_manaer.py
create sql server cloud service
=> create sql server cloud service

src/spaceone/inventory/libs/schema/cloud_service.py, src/spaceone/inventory/manager/disk_manager.py, src/spaceone/inventory/manager/loadbalancer_manager.py, src/spaceone/inventory/manager/snapshot_manager.py, src/spaceone/inventory/manager/sql_server_manager.py, src/spaceone/inventory/manager/vmscaleset_manager.py, src/spaceone/inventory/model/disk/cloud_service.py, src/spaceone/inventory/model/loadbalancer/cloud_service.py, src/spaceone/inventory/model/snapshot/cloud_service.py, src/spaceone/inventory/model/sqlserver/cloud_service.py, src/spaceone/inventory/model/vmscaleset/cloud_service.py
- Disk
- Snapshot
- SQLServer, SQLDatabase
- LoadBalancer
- VMScaleSet
=> Add identifier key : name for azure-cloud-services

README.md, src/spaceone/inventory/service/collector_service.py
Update service to non-threads manager executes
=>  Update service to non-threads manager executes

src/spaceone/inventory/model/keyvault/cloud_service.py, src/spaceone/inventory/model/keyvault/data.py
=> fix: update modeling key data for invisible data in secrets, certificates

src/spaceone/inventory/model/keyvault/cloud_service.py
=> fix : remove thumbprint data from keyvault certificates

src/spaceone/inventory/model/keyvault/cloud_service.py, src/spaceone/inventory/model/keyvault/data.py
=> fix: remove thumbprint from key vault

pkg/pip_requirements.txt, src/spaceone/inventory/connector/__init__.py, src/spaceone/inventory/connector/mysql_server.py, src/spaceone/inventory/connector/nat_gateway.py, src/spaceone/inventory/error/custom.py, src/spaceone/inventory/libs/connector.py, src/spaceone/inventory/manager/__init__.py, src/spaceone/inventory/manager/application_gateway_manager.py, src/spaceone/inventory/manager/disk_manager.py, src/spaceone/inventory/manager/key_vault_manager.py, src/spaceone/inventory/manager/loadbalancer_manager.py, src/spaceone/inventory/manager/mysql_server_manager.py, src/spaceone/inventory/manager/nat_gateway_manager.py, src/spaceone/inventory/manager/network_security_group_manager.py, src/spaceone/inventory/manager/public_ip_address_manager.py, src/spaceone/inventory/manager/snapshot_manager.py, src/spaceone/inventory/manager/sql_server_manager.py, src/spaceone/inventory/manager/storage_account_manager.py, src/spaceone/inventory/manager/subscription_manager.py, src/spaceone/inventory/manager/virtual_network_manager.py, src/spaceone/inventory/manager/vmscaleset_manager.py, src/spaceone/inventory/model/keyvault/cloud_service_type.py, src/spaceone/inventory/model/mysqlserver/cloud_service.py, src/spaceone/inventory/model/mysqlserver/cloud_service_type.py, src/spaceone/inventory/model/mysqlserver/data.py, src/spaceone/inventory/service/collector_service.py, test/manager/test_mysql_server_manager.py
- Add mysql servers to azure cloud services
- Add error class
=> [CLOUD-4709] feat: add mysql servers to azure cloud services

src/spaceone/inventory/libs/manager.py, src/spaceone/inventory/manager/application_gateway_manager.py, src/spaceone/inventory/manager/disk_manager.py, src/spaceone/inventory/manager/key_vault_manager.py, src/spaceone/inventory/manager/loadbalancer_manager.py, src/spaceone/inventory/manager/mysql_server_manager.py, src/spaceone/inventory/manager/nat_gateway_manager.py, src/spaceone/inventory/manager/network_security_group_manager.py, src/spaceone/inventory/manager/public_ip_address_manager.py, src/spaceone/inventory/manager/snapshot_manager.py, src/spaceone/inventory/manager/sql_server_manager.py, src/spaceone/inventory/manager/storage_account_manager.py, src/spaceone/inventory/manager/virtual_network_manager.py, src/spaceone/inventory/manager/vmscaleset_manager.py, src/spaceone/inventory/model/mysqlserver/cloud_service.py
- mysql server invisible data bug fix
-
=> #135 refactor: parsing resource group from id function as a library and mysql servers bug-fix

src/spaceone/inventory/model/mysqlserver/cloud_service.py, src/spaceone/inventory/model/mysqlserver/cloud_service_type.py
- Add optional fields to mysql server cloud services
=> refactor: add optional fields, change to enum field

.github/workflows/CI_branch_tagging.yml
=> build: update CI_branch_tagging(Add ecr upload)

.github/workflows/CI_branch_tagging.yml
=> bug: build ecr repo error

pkg/pip_requirements.txt, src/spaceone/inventory/connector/__init__.py, src/spaceone/inventory/connector/cosmos_db.py, src/spaceone/inventory/error/custom.py, src/spaceone/inventory/libs/connector.py, src/spaceone/inventory/manager/__init__.py, src/spaceone/inventory/manager/cosmos_db_manager.py, src/spaceone/inventory/model/cosmosdb/cloud_service.py, src/spaceone/inventory/model/cosmosdb/cloud_service_type.py, src/spaceone/inventory/model/cosmosdb/data.py, src/spaceone/inventory/model/mysqlserver/cloud_service.py, src/spaceone/inventory/model/mysqlserver/cloud_service_type.py, src/spaceone/inventory/service/collector_service.py, test/manager/test_cosmos_db_manager.py
=> feat: Add azure cosmosdb cloud service

src/spaceone/inventory/model/cosmosdb/cloud_service.py, src/spaceone/inventory/model/cosmosdb/cloud_service_type.py, src/spaceone/inventory/model/cosmosdb/data.py
데이터 안보이는 것들 버그 픽스입니다. 메인 피쳐에 큰 영향 없는 작업이라 빠르게 merge admin으로 제가 진행할께요.
=> fix: bug fix for non-visible data

src/spaceone/inventory/model/postgresqlserver/cloud_service_type.py, src/spaceone/inventory/model/vmscaleset/cloud_service_type.py
=> refactor: add is_optional fields

src/spaceone/inventory/model/postgresqlserver/cloud_service.py, src/spaceone/inventory/model/postgresqlserver/cloud_service_type.py, src/spaceone/inventory/model/vmscaleset/cloud_service_type.py
=> #148 feat: add postgresql cloud service 

README.md, src/spaceone/inventory/conf/cloud_service_conf.py, src/spaceone/inventory/manager/disk_manager.py, src/spaceone/inventory/manager/snapshot_manager.py, src/spaceone/inventory/manager/sql_server_manager.py, src/spaceone/inventory/service/collector_service.py, test/api/test_cloudservice_api.py
=> #162 [CLOUD-5886] feat: add cloud_service_types in options

src/spaceone/inventory/libs/schema/base.py, src/spaceone/inventory/libs/schema/cloud_service_type.py, src/spaceone/inventory/libs/schema/metadata/dynamic_widget.py
feat: add DynamicWidget libraries
=> feat: add DynamicWidget libraries

src/spaceone/inventory/model/keyvault/cloud_service_type.py, src/spaceone/inventory/model/storageaccount/cloud_service_type.py
refactor: update is_primary is True (KeyVault,  StorageeAccount)
=> refactor: update is_primary is True (KeyVault,  StorageeAccount)

src/setup.py, src/spaceone/inventory/libs/schema/metadata/dynamic_widget.py, src/spaceone/inventory/libs/utils.py, src/spaceone/inventory/model/applicationgateway/cloud_service_type.py, src/spaceone/inventory/model/cosmosdb/cloud_service_type.py, src/spaceone/inventory/model/disk/cloud_service_type.py, src/spaceone/inventory/model/disk/widget/disk_count_per_resource_group.yaml, src/spaceone/inventory/model/disk/widget/disk_total_size.yaml, src/spaceone/inventory/model/disk/widget/disk_total_size_per_location.yaml, src/spaceone/inventory/model/disk/widget/disk_total_size_per_status.yaml, src/spaceone/inventory/model/disk/widget/disk_total_size_per_subscription.yaml, src/spaceone/inventory/model/disk/widget/disk_total_size_per_type.yaml, src/spaceone/inventory/model/keyvault/cloud_service_type.py, src/spaceone/inventory/model/loadbalancer/cloud_service_type.py, src/spaceone/inventory/model/mysqlserver/cloud_service_type.py, src/spaceone/inventory/model/natgateway/cloud_service_type.py, src/spaceone/inventory/model/networksecuritygroup/cloud_service_type.py, src/spaceone/inventory/model/postgresqlserver/cloud_service_type.py, src/spaceone/inventory/model/publicipaddress/cloud_service_type.py, src/spaceone/inventory/model/snapshot/cloud_service_type.py, src/spaceone/inventory/model/sqldatabase/cloud_service_type.py, src/spaceone/inventory/model/sqlserver/cloud_service_type.py, src/spaceone/inventory/model/storageaccount/cloud_service_type.py, src/spaceone/inventory/model/virtualnetwork/cloud_service_type.py, src/spaceone/inventory/model/vmscaleset/cloud_service_type.py
feat: add dynamic widget query
feat: add package_data in setup.py for query yaml file
feat: add utils for cloud service
fix: update query aws to azure
=> feat: add dynamic widget query

README.md, src/spaceone/inventory/conf/cloud_service_conf.py, src/spaceone/inventory/manager/application_gateway_manager.py, src/spaceone/inventory/manager/cosmos_db_manager.py
=> build: branch fix

src/spaceone/inventory/model/vmscaleset/widget/vmscaleset_total_vm_count.yaml
=> fix: vmss count query bug

README.md
docs: add endpoint information in README
=> docs: add endpoint information in README

src/spaceone/inventory/libs/manager.py, src/spaceone/inventory/service/collector_service.py
feat: add feature service_code_mappers in options
[Azure Cloud] Add option to change service code in collector plugin (#186)
=> feat: add feature service_code_mappers in options
